### ISSUE TITLE
homebrew Error: Version value must be a string; got a Float (6.0)

### ISSUE THREAD

**Issue by kmag** [macmade/thx#2]
The current homebrew formula appears broken.  It seems you forgot quotes around your version number.

$ brew install --HEAD macmade/tap/xrun
...
==> Installing xrun from macmade/tap
Error: Version value must be a string; got a Float (6.0)
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Homebrew/version.rb:369:in `initialize'
/usr/local/Homebrew/Library/Homebrew/requirements/xcode_requirement.rb:26:in `new'
/usr/local/Homebrew/Library/Homebrew/requirements/xcode_requirement.rb:26:in `message'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:408:in `block (2 levels) in check_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:405:in `each'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:405:in `block in check_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:404:in `each_pair'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:404:in `check_requirements'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:377:in `compute_dependencies'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:141:in `verify_deps_exist'
/usr/local/Homebrew/Library/Homebrew/formula_installer.rb:134:in `prelude'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:323:in `install_formula'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:256:in `block in install'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:254:in `each'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:254:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'

**Comment by macmade** [comment]
Thanks for the report, this has been fixed. : )
